//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onvatry.FormationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormationService.FormationSoap")]
    public interface FormationSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetInstructionsStep1Result de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep1", ReplyAction="*")]
        Onvatry.FormationService.GetInstructionsStep1Response GetInstructionsStep1(Onvatry.FormationService.GetInstructionsStep1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep1", ReplyAction="*")]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep1Response> GetInstructionsStep1Async(Onvatry.FormationService.GetInstructionsStep1Request request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetKeyResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKey", ReplyAction="*")]
        Onvatry.FormationService.GetKeyResponse GetKey(Onvatry.FormationService.GetKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetKeyResponse> GetKeyAsync(Onvatry.FormationService.GetKeyRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetInstructionsStep2Result de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep2", ReplyAction="*")]
        Onvatry.FormationService.GetInstructionsStep2Response GetInstructionsStep2(Onvatry.FormationService.GetInstructionsStep2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep2", ReplyAction="*")]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep2Response> GetInstructionsStep2Async(Onvatry.FormationService.GetInstructionsStep2Request request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément password de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep3", ReplyAction="*")]
        Onvatry.FormationService.GetInstructionsStep3Response GetInstructionsStep3(Onvatry.FormationService.GetInstructionsStep3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep3", ReplyAction="*")]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep3Response> GetInstructionsStep3Async(Onvatry.FormationService.GetInstructionsStep3Request request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément answer de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep4", ReplyAction="*")]
        Onvatry.FormationService.GetInstructionsStep4Response GetInstructionsStep4(Onvatry.FormationService.GetInstructionsStep4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstructionsStep4", ReplyAction="*")]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep4Response> GetInstructionsStep4Async(Onvatry.FormationService.GetInstructionsStep4Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep1", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep1RequestBody Body;
        
        public GetInstructionsStep1Request() {
        }
        
        public GetInstructionsStep1Request(Onvatry.FormationService.GetInstructionsStep1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInstructionsStep1RequestBody {
        
        public GetInstructionsStep1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep1Response", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep1ResponseBody Body;
        
        public GetInstructionsStep1Response() {
        }
        
        public GetInstructionsStep1Response(Onvatry.FormationService.GetInstructionsStep1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInstructionsStep1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Onvatry.FormationService.ArrayOfString GetInstructionsStep1Result;
        
        public GetInstructionsStep1ResponseBody() {
        }
        
        public GetInstructionsStep1ResponseBody(Onvatry.FormationService.ArrayOfString GetInstructionsStep1Result) {
            this.GetInstructionsStep1Result = GetInstructionsStep1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKey", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetKeyRequestBody Body;
        
        public GetKeyRequest() {
        }
        
        public GetKeyRequest(Onvatry.FormationService.GetKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKeyRequestBody {
        
        public GetKeyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetKeyResponseBody Body;
        
        public GetKeyResponse() {
        }
        
        public GetKeyResponse(Onvatry.FormationService.GetKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetKeyResult;
        
        public GetKeyResponseBody() {
        }
        
        public GetKeyResponseBody(string GetKeyResult) {
            this.GetKeyResult = GetKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep2", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep2RequestBody Body;
        
        public GetInstructionsStep2Request() {
        }
        
        public GetInstructionsStep2Request(Onvatry.FormationService.GetInstructionsStep2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInstructionsStep2RequestBody {
        
        public GetInstructionsStep2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep2Response", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep2ResponseBody Body;
        
        public GetInstructionsStep2Response() {
        }
        
        public GetInstructionsStep2Response(Onvatry.FormationService.GetInstructionsStep2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInstructionsStep2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetInstructionsStep2Result;
        
        public GetInstructionsStep2ResponseBody() {
        }
        
        public GetInstructionsStep2ResponseBody(byte[] GetInstructionsStep2Result) {
            this.GetInstructionsStep2Result = GetInstructionsStep2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep3", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep3RequestBody Body;
        
        public GetInstructionsStep3Request() {
        }
        
        public GetInstructionsStep3Request(Onvatry.FormationService.GetInstructionsStep3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInstructionsStep3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        public GetInstructionsStep3RequestBody() {
        }
        
        public GetInstructionsStep3RequestBody(string password) {
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep3Response", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep3ResponseBody Body;
        
        public GetInstructionsStep3Response() {
        }
        
        public GetInstructionsStep3Response(Onvatry.FormationService.GetInstructionsStep3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInstructionsStep3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Onvatry.FormationService.ArrayOfString GetInstructionsStep3Result;
        
        public GetInstructionsStep3ResponseBody() {
        }
        
        public GetInstructionsStep3ResponseBody(Onvatry.FormationService.ArrayOfString GetInstructionsStep3Result) {
            this.GetInstructionsStep3Result = GetInstructionsStep3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep4Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep4", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep4RequestBody Body;
        
        public GetInstructionsStep4Request() {
        }
        
        public GetInstructionsStep4Request(Onvatry.FormationService.GetInstructionsStep4RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInstructionsStep4RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string answer;
        
        public GetInstructionsStep4RequestBody() {
        }
        
        public GetInstructionsStep4RequestBody(string answer) {
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstructionsStep4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstructionsStep4Response", Namespace="http://tempuri.org/", Order=0)]
        public Onvatry.FormationService.GetInstructionsStep4ResponseBody Body;
        
        public GetInstructionsStep4Response() {
        }
        
        public GetInstructionsStep4Response(Onvatry.FormationService.GetInstructionsStep4ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInstructionsStep4ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Onvatry.FormationService.ArrayOfString GetInstructionsStep4Result;
        
        public GetInstructionsStep4ResponseBody() {
        }
        
        public GetInstructionsStep4ResponseBody(Onvatry.FormationService.ArrayOfString GetInstructionsStep4Result) {
            this.GetInstructionsStep4Result = GetInstructionsStep4Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FormationSoapChannel : Onvatry.FormationService.FormationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormationSoapClient : System.ServiceModel.ClientBase<Onvatry.FormationService.FormationSoap>, Onvatry.FormationService.FormationSoap {
        
        public FormationSoapClient() {
        }
        
        public FormationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onvatry.FormationService.GetInstructionsStep1Response Onvatry.FormationService.FormationSoap.GetInstructionsStep1(Onvatry.FormationService.GetInstructionsStep1Request request) {
            return base.Channel.GetInstructionsStep1(request);
        }
        
        public Onvatry.FormationService.ArrayOfString GetInstructionsStep1() {
            Onvatry.FormationService.GetInstructionsStep1Request inValue = new Onvatry.FormationService.GetInstructionsStep1Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep1RequestBody();
            Onvatry.FormationService.GetInstructionsStep1Response retVal = ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep1(inValue);
            return retVal.Body.GetInstructionsStep1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep1Response> Onvatry.FormationService.FormationSoap.GetInstructionsStep1Async(Onvatry.FormationService.GetInstructionsStep1Request request) {
            return base.Channel.GetInstructionsStep1Async(request);
        }
        
        public System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep1Response> GetInstructionsStep1Async() {
            Onvatry.FormationService.GetInstructionsStep1Request inValue = new Onvatry.FormationService.GetInstructionsStep1Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep1RequestBody();
            return ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onvatry.FormationService.GetKeyResponse Onvatry.FormationService.FormationSoap.GetKey(Onvatry.FormationService.GetKeyRequest request) {
            return base.Channel.GetKey(request);
        }
        
        public string GetKey() {
            Onvatry.FormationService.GetKeyRequest inValue = new Onvatry.FormationService.GetKeyRequest();
            inValue.Body = new Onvatry.FormationService.GetKeyRequestBody();
            Onvatry.FormationService.GetKeyResponse retVal = ((Onvatry.FormationService.FormationSoap)(this)).GetKey(inValue);
            return retVal.Body.GetKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetKeyResponse> Onvatry.FormationService.FormationSoap.GetKeyAsync(Onvatry.FormationService.GetKeyRequest request) {
            return base.Channel.GetKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Onvatry.FormationService.GetKeyResponse> GetKeyAsync() {
            Onvatry.FormationService.GetKeyRequest inValue = new Onvatry.FormationService.GetKeyRequest();
            inValue.Body = new Onvatry.FormationService.GetKeyRequestBody();
            return ((Onvatry.FormationService.FormationSoap)(this)).GetKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onvatry.FormationService.GetInstructionsStep2Response Onvatry.FormationService.FormationSoap.GetInstructionsStep2(Onvatry.FormationService.GetInstructionsStep2Request request) {
            return base.Channel.GetInstructionsStep2(request);
        }
        
        public byte[] GetInstructionsStep2() {
            Onvatry.FormationService.GetInstructionsStep2Request inValue = new Onvatry.FormationService.GetInstructionsStep2Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep2RequestBody();
            Onvatry.FormationService.GetInstructionsStep2Response retVal = ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep2(inValue);
            return retVal.Body.GetInstructionsStep2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep2Response> Onvatry.FormationService.FormationSoap.GetInstructionsStep2Async(Onvatry.FormationService.GetInstructionsStep2Request request) {
            return base.Channel.GetInstructionsStep2Async(request);
        }
        
        public System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep2Response> GetInstructionsStep2Async() {
            Onvatry.FormationService.GetInstructionsStep2Request inValue = new Onvatry.FormationService.GetInstructionsStep2Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep2RequestBody();
            return ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onvatry.FormationService.GetInstructionsStep3Response Onvatry.FormationService.FormationSoap.GetInstructionsStep3(Onvatry.FormationService.GetInstructionsStep3Request request) {
            return base.Channel.GetInstructionsStep3(request);
        }
        
        public Onvatry.FormationService.ArrayOfString GetInstructionsStep3(string password) {
            Onvatry.FormationService.GetInstructionsStep3Request inValue = new Onvatry.FormationService.GetInstructionsStep3Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep3RequestBody();
            inValue.Body.password = password;
            Onvatry.FormationService.GetInstructionsStep3Response retVal = ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep3(inValue);
            return retVal.Body.GetInstructionsStep3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep3Response> Onvatry.FormationService.FormationSoap.GetInstructionsStep3Async(Onvatry.FormationService.GetInstructionsStep3Request request) {
            return base.Channel.GetInstructionsStep3Async(request);
        }
        
        public System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep3Response> GetInstructionsStep3Async(string password) {
            Onvatry.FormationService.GetInstructionsStep3Request inValue = new Onvatry.FormationService.GetInstructionsStep3Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep3RequestBody();
            inValue.Body.password = password;
            return ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onvatry.FormationService.GetInstructionsStep4Response Onvatry.FormationService.FormationSoap.GetInstructionsStep4(Onvatry.FormationService.GetInstructionsStep4Request request) {
            return base.Channel.GetInstructionsStep4(request);
        }
        
        public Onvatry.FormationService.ArrayOfString GetInstructionsStep4(string answer) {
            Onvatry.FormationService.GetInstructionsStep4Request inValue = new Onvatry.FormationService.GetInstructionsStep4Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep4RequestBody();
            inValue.Body.answer = answer;
            Onvatry.FormationService.GetInstructionsStep4Response retVal = ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep4(inValue);
            return retVal.Body.GetInstructionsStep4Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep4Response> Onvatry.FormationService.FormationSoap.GetInstructionsStep4Async(Onvatry.FormationService.GetInstructionsStep4Request request) {
            return base.Channel.GetInstructionsStep4Async(request);
        }
        
        public System.Threading.Tasks.Task<Onvatry.FormationService.GetInstructionsStep4Response> GetInstructionsStep4Async(string answer) {
            Onvatry.FormationService.GetInstructionsStep4Request inValue = new Onvatry.FormationService.GetInstructionsStep4Request();
            inValue.Body = new Onvatry.FormationService.GetInstructionsStep4RequestBody();
            inValue.Body.answer = answer;
            return ((Onvatry.FormationService.FormationSoap)(this)).GetInstructionsStep4Async(inValue);
        }
    }
}
